.test_template: &test_definition
  script:
    - python -V  # Print out python version for debugging
    - python -m pip install -U pip
    - pip install .
    - cd tests
    - pytest
  rules:
    - changes:
      - tests/*
      - chiLife/data/*
      - chiLife/*.py


test:3.8:
  image: python:3.8
  <<: *test_definition

test:3.9:
  image: python:3.9
  <<: *test_definition

test:3.10:
  image: python:3.10
  <<: *test_definition

    # test:3.11:
    #   image: python:3.11
    #   <<: *test_definition

test:win:
  image: python:3.10-windowsservercore-ltsc2022
  tags: 
    - windows
  <<: *test_definition

.build_template: &build_definition
  script:
    - python setup.py bdist_wheel
    # an alternative approach is to install and run:
    - pip install dist/*
    # run the command here
  artifacts:
    paths:
      - dist/*.whl

  #run:3.8:
  #  image: python:3.8
  #  <<: *build_definition
  
  #run:3.9:
  #  image: python:3.8
  #   <<: *build_definition
  #  
