name: Test on PR activity
on:
  pull_request:
    branches:
    - "**"

  workflow_dispatch:
    inputs:
      myCommit:
        description: 'Commit SHA1'
        required: true
        default: 'undefined'
        type: string


jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      
      - name: Test with pytest
        run: |
          cd tests
          pytest
